---

version: '3'

services:
    plex:
      image: linuxserver/plex:latest
      container_name: plex
      network_mode: host
      environment:
         PUID: 1000
         PGID: 1000
         VERSION: docker
         TZ: Europe/Moscow
      volumes:
        - "./config/plex:/config"
        - "./media:/media"
      ports:
        - 32400:32400
        - 32400:32400/udp
        - 32469:32469
        - 32469:32469/udp
        - 5353:5353/udp
        - 1900:1900/udp
      restart: always

    deluge:
      image: linuxserver/deluge
      container_name: deluge
      network_mode: host
      restart: always
      volumes:
        - "./config/deluge:/config"
        - "./downloads:/downloads"
        - "./media:/media"
      ports:
         - "8112:8112"
         - "58846:58846"
         - "58847:58847"
         - "58847:58847/udp"
      environment:
         PUID: 1000
         PGID: 1000
         TZ: Europe/Moscow
